# -*- coding: utf-8 -*-
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Documentation'
copyright = '2020, NETPIE'
author = 'NETPIE'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',

]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# -- Customize Config For NEXPIE Site ----------------------------------------
# --- NEXPIE
portal_domain = 'https://portal.netpie.io'
broker_domain = 'mqtt.netpie.io'
auth_domain = 'https://authx.netpie.io'
rest_domain = 'https://api.netpie.io/v2/device'
rest_domain2 = 'api.netpie.io/v2/device'
feed_domain = 'https://ds.netpie.io/feed'
feed_domain2 = 'ds.netpie.io/feed'
platform_name = 'NETPIE'
coap_domain = 'coap://coap.netpie.io'
swagger_part = '(ทดสอบการทำงานของ API ได้ที่  https://trial-api.netpie.io/)'
tag_project = '50'
tag_device = '10'
#gql_domain = ''
#swagger_part = ''

rst_prolog = """
.. |portal_url| replace:: {0}
.. |broker_url| replace:: {1}
.. |auth_url| replace:: {2}
.. |rest_url| replace:: {3}
.. |rest_url2| replace:: {4}
.. |feed_url| replace:: {5}
.. |feed_url2| replace:: {6}
.. |platform_name| replace:: {7}
.. |coap_url| replace:: {8}
.. |swagger_part| replace:: {9}
.. |tag_project| replace:: {10}
.. |tag_device| replace:: {11}
""".format(
portal_domain, 
broker_domain,
auth_domain, 
rest_domain,
rest_domain2,
feed_domain,
feed_domain2,
platform_name,
coap_domain,
swagger_part,
tag_project,
tag_device 
)

# -- Customize Config For NEXPIE Site ----------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme = 'press'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ["netpietheme.css","custom.css",'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}
#---sphinx-themes-----

html_theme_options = {
  "external_links": [
      ("<i class='fa fa-facebook-square'></i>", "https://www.facebook.com/groups/netpie/"),
      ("<i class='fa fa-youtube-play'></i>", "https://www.youtube.com/channel/UCUx4rX08qf3rFdviFymCtZw"),
      ("<i class='fa fa-book'></i>", "https://netpie.io/guide"),
      ("<i class='fa fa-envelope'></i>", "mailto:contact@nexpie.com")
  ]
}

html_logo = '_static/netpie-logo.png'
html_favicon = '_static/netpie_favicon.png'


